DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS profession;

CREATE TABLE IF NOT EXISTS profession(
    id BIGINT generated by default as identity (start with 1) primary key,
    name varchar(100) not null
);

CREATE TABLE IF NOT EXISTS person(
    id BIGINT generated by default as identity (start with 1) primary key,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL CHECK(age >= 1 and age <= 100),
    profession_id BIGINT, FOREIGN KEY (profession_id) REFERENCES profession(id)
);
